### ISSUE TITLE
Support for key-vault?

### ISSUE THREAD

**Issue by winding-lines** [MindFlavor/AzureSDKForRust#112]
Many thanks for creating this library! What are your thoughts/plans around supporting [key-vault](https://azure.microsoft.com/en-us/pricing/details/key-vault/)? 

I have not looked at the implementation yet, not sure if there is a rest api or something else.

Marius

**Comment by karataliu** [comment]
KeyVault shares ARM REST api for management plane, and has its own REST API for data plane
https://docs.microsoft.com/en-us/rest/api/keyvault/
https://docs.microsoft.com/en-us/azure/key-vault/key-vault-secure-your-key-vault#the-management-plane-and-the-data-plane

Since key-vault and other ARM service relies on AAD, a more fundamental requirement is AAD support.
I'd be readily to take a look at ADD support in recent.

**Comment by MindFlavor** [comment]
Yes, @karataliu is right, we need some kind of AAD support. Maybe we can start by simply exposing methods that accept the bearer token and, in a second iteration, integrate the OAuth workflow in the SDK. I'll try to sketch something and let you know.

**Comment by guywaldman** [comment]
You can use https://github.com/guywaldman/azure-sdk-keyvault 😊

**Comment by MindFlavor** [comment]
If @guywaldman agrees we could add the link of his crate to this repo's README to improve discoverability.

**Comment by guywaldman** [comment]
@MindFlavor of course 👍
