### ISSUE TITLE
Support Custom Cosmos DB Base URI

### ISSUE THREAD

**Issue by zimingWu** [MindFlavor/AzureSDKForRust#129]
Base uri is hard-coded  with "documents.azure.com". But the URI of Azure Cosmos DB China is 'documents.azure.cn:10255'. Also developing with Cosmos DB Local Emulator needs to custom base URI, like "my-local-emulator:port".

Maybe add base Uri as an option in AuthorizationToken?

**Comment by MindFlavor** [comment]
It's a good idea to make the Uri configurable.

**Comment by MindFlavor** [comment]
I am working on it in the [issue/129/dev](https://github.com/MindFlavor/AzureSDKForRust/tree/issue/129/dev) branch. I still have to check the tests and the resulting syntax is a bit cumbersome but it should be flexible.

**Comment by MindFlavor** [comment]
I have a viable implementation in [https://github.com/MindFlavor/AzureSDKForRust/pull/131](https://github.com/MindFlavor/AzureSDKForRust/pull/131). It's not backward compatible, you will have to use `ClientBuilder::new` instead of `Client::new` but it now supports:

* Default URI (as before)
* China URI
* Emulator URI
* Custom URI

I haven't checked it enough (I will at least test the emulator as soon as I have a windows machine at hand) so I like feedback if possibile!

**Comment by zimingWu** [comment]
Thanks a lot, with configurable Uri, I can migrate my application to rust now.

`ClientBuilder::new_china` is not working.
Sorry, it's my mistake.
Port 10255 is for China mongodb api.
China rest api uri should be `https://{account-name}.documents.azure.cn`

**Comment by MindFlavor** [comment]
Thank you!
