### ISSUE TITLE
get_blob() error running in Ubuntu/Docker

### ISSUE THREAD

**Issue by roqvist** [MindFlavor/AzureSDKForRust#223]
I upgraded from version 0.23 to latest versions and get the following error when I try to retrieve a blob. This problem only occurs in when running in an Ubuntu Docker image. Running locally on my Windows machine, everything works fine.

This code worked in the Docker environment before upgrading.

Have some third party software/libraries been added as a required dependency for Linux lately? The Ubuntu Docker image I'm using has always had OpenSSL 1.1 installed.

```
    let response = storage_client
        .get_blob()
        .with_container_name(container_name)
        .with_blob_name(blob_name)
        .finalize()
        .await?;
```

```
thread 'actix-rt:worker:0' panicked at 'called `Result::unwrap()` on an `Err` value: HyperError(hyper::Error(Connect, Custom { kind: Other, error: Custom { kind: InvalidData, error: WebPKIError(UnknownIssuer) } }))', src/libcore/result.rs:1165:5
```

**Comment by MindFlavor** [comment]
We use [hyper-rustls](https://github.com/ctz/hyper-rustls) which in turn depends on [rustls](https://github.com/ctz/rustls) (in order to avoid using OpenSSL). It seems that hyper-rustls now uses [rustls-native-certs](https://github.com/ctz/rustls-native-certs) (since version 0.18.0) which in turn uses [openssl-probe](https://github.com/alexcrichton/openssl-probe) on Linux (so we are back at OpenSSL after all). On Windows it uses schannel instead.

My - wild - guess is that you have an outdated cert root store in your container.

**Comment by roqvist** [comment]
Thanks alot, `update-ca-certificates` on the container did the trick! Closing this.
