### ISSUE TITLE
list_blobs get max results need some help

### ISSUE THREAD

**Issue by jayhuang75** [MindFlavor/AzureSDKForRust#251]
Hello @MindFlavor, this is a really great SDK, thank you for doing this. 

I have a quick question when I try to get all the blobs list return around 150K, just simple count, and always get back the default 5000 back. is there any I have done it wrong, please kindly advice. 

`
let max_results:u32 = 150000;

    let iv = client
        .list_blobs()
        .with_container_name("data")
        .with_max_results(max_results)
        .finalize()
        .await?;`

**Comment by MindFlavor** [comment]
Hi @jayhuang75, no you are not doing anything wrong! It's just that the List Blobs REST API poses a soft limit on the number of returned items from a single call (5000 as you have found out yourself). You can find the details here [https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs#uri-parameters](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs#uri-parameters).

In order to enumerate the remaining items you should call the same function again passing the continuation token (next marker). Ideally you should use the `stream` function that takes care for you. The problem is I haven't implemented it yet 🤦‍♂ . I'll try to do it ASAP!

**Comment by MindFlavor** [comment]
In the aforementioned PR I'm implementing the `stream` function that will help achieve what you want. I just need to add an example/E2E test before publishing it.

**Comment by MindFlavor** [comment]
I've merged the stream function. You can find a complete example here: [AzureSDKForRust/blob/master/azure_sdk_storage_blob/examples/list_blobs00.rs](https://github.com/MindFlavor/AzureSDKForRust/blob/master/azure_sdk_storage_blob/examples/list_blobs00.rs). 

In a nutshell, all you have to do is to call the `stream` function instead of the `finalize` one.  Then you cycle with a `while let Some` loop until you exhaust the blobs (you can bail out prematurely if you want of course). The SDK will take care of passing the REST API the `next marker` token so subsequent calls will return more items.

```rust
let mut stream = Box::pin(
  client
    .list_blobs()
    .with_container_name(&container_name)
    stream(),
);

while let Some(value) = stream.next().await {
  // process the item
}
```

PS: The pinning is necessary so you cannot move the request around.

Hope it helps!

**Comment by jayhuang75** [comment]
@MindFlavor , you are the man. really appreciated your speed reply and implementation, I will give a try. And please kindly stay safe and healthy. Code Strong.

**Comment by jayhuang75** [comment]
@MindFlavor , just give a try, all good. Thank you so much for your help and guidance here.
```
received 5000 blobs
received 5000 blobs
received 3521 blobs
blob count 3
return from azure is: Ok(())
Time elapsed in run() is: 14.85018204s
```
